### ISSUE TITLE
Don't create snapshots in a failed test

### ISSUE THREAD

**Issue by wgoodall01** [bradleyjkemp/cupaloy#31]
While writing a bunch of tests, I noticed that Cupaloy will still write snapshots on the first invocation of a test, even if that test has already failed. For instance:

```
func TestShouldNotWriteSnapshot(t *testing.T) {
	t.Fail()
	cupaloy.SnapshotT(t, "bad snapshot")
}
```
will still log:
```
--- FAIL: TestShouldNotWriteSnapshot (0.00s)
	board_test.go:199: snapshot created for test TestShouldNotWriteSnapshot
```
and write a snapshot to `.snapshots/TestShouldNotWriteSnapshot`.

I'm not sure if this is the intended behavior or not, but it seems like a bad idea to write snapshots for a test that is known to have failed. Maybe we should check `t.Failed()` inside `cupaloy.SnapshotT`?

**Comment by bradleyjkemp** [comment]
Agreed! Seems sensible that SnapshotT should return immediately if the test has already failed.
I don't think anyone would expect a snapshot to be created/updated if the test had failed
