### ISSUE TITLE
Fix Sourcegraph badge

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/cupaloy#36]
The badge endpoint takes a long time to respond and so cloudflare returns a 500, this then seems to get cached by GitHub as a broken/missing image.

**Comment by sqs** [comment]
We made the Sourcegraph badges significantly faster a short while after you posted this. Sorry for the slowness.

**Comment by bradleyjkemp** [comment]
Thanks! All seems to be working great now
