### ISSUE TITLE
Use of internal package not allowed

### ISSUE THREAD

**Issue by cyberxander90** [bradleyjkemp/cupaloy#57]
After installing this package using [govendor](https://github.com/kardianos/govendor/wiki/Govendor-CheatSheet) running the tests it fails with the error
```
package command-line-arguments (test)
        imports github.com/bradleyjkemp/cupaloy
        imports github.com/bradleyjkemp/cupaloy/v2/internal: use of internal package github.com/bradleyjkemp/cupaloy/internal not allowed
FAIL    command-line-arguments [setup failed]
```

**Comment by bradleyjkemp** [comment]
This package is now using Go modules so you could you try using the import path `github.com/bradleyjkemp/cupaloy/v2` instead?

Just realised the installation instructions in the README are out of date, I'll update those now!

**Comment by bradleyjkemp** [comment]
Closing as this is not an issue when using modern Go dependency managers and looks like you've mitigated this yourself by forking the repo.
