### ISSUE TITLE
Allow ignoring contents of specific structure fields

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/cupaloy#6]
Some struct fields might be known and intended to not remain constant between test runs. It would then be required to ignore these fields (perhaps just by overwriting with a constant value)
Arguably tests should be deterministic though.

**Comment by bradleyjkemp** [comment]
Outside scope of this project: should be a separate tool

**Comment by eikc** [comment]
Hey @bradleyjkemp 

I'm wondering if you have any good ideas on ignoring a field in a struct? For my use case I have an ID, created and upated fields which is random everytime i run the test.

Now i could create an anonymous struct with all the fields that do not change and then take a snapshot of that. But I'm afraid that if I later add a new field to my given domain class and forget to update the test, then everything continue to pass but without recording the new field. 

Do you have any good ideas on how to fix this "issue"? Looking forward to hear from you and keep up the good work with the library, I like it a lot :-)

**Comment by bradleyjkemp** [comment]
Hi @eikc, this is unfortunately the hardest part of snapshot testing. Within my experience I've come up with a few different ways of approaching this:
* Design the system to avoid non-determinism. Where possible I use a library like https://github.com/jonboulle/clockwork to be able to inject predictable timestamps for tests and I can imagine coming up with something similar for IDs.
This is obviously a very heavyweight solution so is probably only worth doing if you other tests require this dependency injection.
* Sanitise data before snapshotting. This is similar to what you suggest: I get some output data that I know contains some unpredictable values and iterate over it to replace all the unpredictable values with constant placeholders.
As you point out, there's a reasonable risk of missing new values if you try to sanitise by copying the known stable values into their own struct so personally I'd recommend the opposite approach of just cleaning up any field that makes the tests fail.
The "separate tool" I referred to in my last comment was planned to be something that would automatically go through and delete any field marked with a specific struct tag but unfortunately I never got round to building this.
* go-spew (the library that is used for actually generating the snapshot data) will automatically use the `String() string` or `Error() string` methods if your field type implements them. So it's possible you could implement one of those on your timestamp/ID and have it return a constant string. This would work but is probably a bad idea because it'll probably cause problems elsewhere (e.g. when you try to print it and *do* want the proper output not the constant string)

Hope this helps! And if I end up building the struct field redactor tool, I'll let you know 🙂

**Comment by bradleyjkemp** [comment]
@eikc I actually had a go at implementing that redactor utility after all: https://github.com/bradleyjkemp/redactif

It's pretty rough (will just ignore maps at the moment) but perhaps you'll find it useful (especially if you've got some deeply nested fields that would be a pain to redact manually) 🙂
