### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by kswope** [bradleyjkemp/cupaloy#74]
docs here https://pkg.go.dev/github.com/pyros2097/cupaloy#section-readme
say use

```
go get -u github.com/bradleyjkemp/cupaloy
```

README on here doesn't even mention how to install.  Not even sure if same package.

I get

```
go get: module github.com/bradleykemp/cupaloy: git ls-remote -q origin in /Users/kevin/.go/pkg/mod/cache/vcs/80d9f6d7d4a4bdada3cd1ba5dfc1c3543d1449b3cb2ccd046ae294400d51c447: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
```

No other package in my current project is having this problem.

However, I got a clue from pkg.go.dev docs 

```
go get github.com/pyros2097/cupaloy
```

which worked.

**Comment by gean-true** [comment]
Not sure if the repo owner's name has change but you report shows on the command log shows a missing "j" between "bradley" and "kemp"

**Comment by kswope** [comment]
> Not sure if the repo owner's name has change but you report shows on the command log shows a missing "j" between "bradley" and "kemp"

Good catch.  My zshrc was mapping jk to enter vim mode, so it was eating the "j" in my terminal.  Its been configured like this for years and this is the only time it seemed to matter!

Closing, but I should point out that the links at the top of

https://pkg.go.dev/github.com/pyros2097/cupaloy#section-readme

```
github.com/pyros2097/cupaloy 
```


are pointing to a github 404, which compounded my confusion.
